home_app/urls.py
from django.urls import path
from . import views

app_name = 'home_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('detail<int:pk>', views.detail, name='detail'),
    path('addtocart<int:pk>', views.add_to_cart, name='addtocart'),
    path('deletefromcart<int:pk>', views.delete, name='deletefromcart'),
    path('womencategory', views.women_category, name='womencategory'),
    path('search', views.search, name='search'),
    path('sportcategory', views.sport_category, name='sportcategory'),
    path('sendmsg', views.send_msg, name='sendmsg'),
    path('showcart', views.show_cart,name='showcart'),
    path('showall', views.all_products,name='all_products')

]

modshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('', include('auth_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_app/models.py
from django.contrib.auth.models import User
from django.db import models



# Create your models here.
class Color(models.Model):
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.color


class Size(models.Model):
    size = models.CharField(max_length=20)

    def __str__(self):
        return self.size


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Product(models.Model):
    image = models.ImageField(upload_to='products')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    colors = models.ManyToManyField(Color)
    size = models.ManyToManyField(Size)

    def __str__(self):
        return self.name


class Order(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    size = models.CharField(max_length=10)
    color = models.CharField(max_length=10)
    total_price = models.IntegerField(default=0)
    price = models.IntegerField(null=True, blank=True)
    quantity = models.IntegerField(default=0)
    product_name = models.CharField(max_length=20)

    class Meta:
        unique_together = ('color', 'size', 'product_name', 'username')

    def __str__(self):
        return self.product_name


class Contact(models.Model):
    name = models.CharField(max_length=20)
    subj = models.CharField(max_length=30)
    msg = models.TextField()
    email = models.CharField(max_length=50)

    def __str__(self):
        return self.name

home_app/views.py
from django.contrib.auth import authenticate
from .models import Product, Order, Contact
from auth_app.models import ImageProcessing
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.core.paginator import Paginator

# Create your views here.

def home(request):
    products = Product.objects.all()
    order = Product.objects.raw('select * from modshopdb.home_app_product order by price DESC')
    return render(request, 'home_app/index.html', {'products': products, 'recent': order})


def detail(request, pk):
    instance = get_object_or_404(Product, id=pk)
    return render(request, 'home_app/detail.html', {'product': instance})


def add_to_cart(request, pk):
    if request.method == 'POST':
        product = Product.objects.get(id=pk)

        quantity, color, size = request.POST.get('quantity'), request.POST.get('color'), request.POST.get('size')
        product_exist = Order.objects.filter(username=request.user, color=color, size=size,
                                             product_name=product.name).exists()
        instance = Order.objects.filter(username=request.user, color=color, size=size,
                                        product_name=product.name)
        print(request.user)

        if product_exist:
            print('ok')
            for order in instance:
                order.quantity += int(quantity)
                print('test2')
                order.total_price += int(quantity) * int(product.price)
                order.save()

        else:
            print('no')

            new_instance = Order.objects.create(username=request.user, color=color, size=size,
                                                product_name=product.name,
                                                quantity=int(quantity), price=int(product.price))
            print('test')
            new_instance.total_price += (int(quantity) * int(new_instance.price))
            new_instance.save()

        products = Order.objects.filter(username=request.user)
        total_prices = 0
        for order in products:
            total_prices += order.total_price

        return render(request, 'home_app/cart.html', {'products': products, 'total': total_prices})
    products = Order.objects.filter(username=request.user)
    total_prices = 0
    for order in products:
        total_prices += order.total_price

    return render(request, 'home_app/cart.html', {'products': products, 'total': total_prices})


def delete(request, pk):
    Order.objects.get(id=pk).delete()
    products = Order.objects.filter(username=request.user)
    total_prices = 0
    for order in products:
        total_prices += order.total_price
    return render(request, 'home_app/cart.html', {'products': products, 'total': total_prices})


def women_category(request):
    search_products = Product.objects.filter(category__name='women')
    products = Product.objects.all()
    order = Product.objects.raw('select * from modshopdb.home_app_product order by price DESC')
    return render(request, 'home_app/index.html', {'products': products, 'recent': order, 'search': search_products})


def sport_category(request):
    search_products = Product.objects.filter(category__name='sport')
    products = Product.objects.all()
    order = Product.objects.raw('select * from modshopdb.home_app_product order by price DESC')
    return render(request, 'home_app/index.html', {'products': products, 'recent': order, 'search': search_products})


def search(request):
    name = request.GET.get('search')
    print(name)
    search_products = Product.objects.raw('select * from modshopdb.home_app_product where name LIKE %s', [f'%{name}%'])
    products = Product.objects.all()
    order = Product.objects.raw('select * from modshopdb.home_app_product order by price DESC')
    return render(request, 'home_app/index.html', {'products': products, 'recent': order, 'search': search_products})


def send_msg(request):
    if request.method == 'POST':
        name, subj, msg, email = request.POST.get('name'), request.POST.get('subj'), request.POST.get(
            'msg'), request.POST.get('email')
        Contact.objects.create(name=name, subj=subj, msg=msg, email=email)
        return render(request, 'home_app/contact.html')

    return render(request, 'home_app/contact.html')


def show_cart(request):
    products = Order.objects.filter(username=request.user)
    total_prices = 0
    for order in products:
        total_prices += order.total_price
    return render(request, 'home_app/cart.html', {'products': products, 'total': total_prices})


def all_products(request):
    colors, sizes, min_price, max_price = request.GET.getlist('color'), request.GET.getlist('size'), request.GET.get(
        'min'), request.GET.get('max')

    products = Product.objects.all()
    if colors:
        products = products.filter(colors__color__in=colors).distinct()
    if sizes:
        products = products.filter(size__size__in=sizes).distinct()
    if max_price and min_price:
        max = int(max_price)
        min = int(min_price)
        products = products.raw('select * from modshopdb.home_app_product where price > %s and price < %s',
                                [min, max])
    paginator = Paginator(products, 1)
    page = request.GET.get('page')
    obj = paginator.get_page(page)

    return render(request, 'home_app/shop.html', {'products': obj})

home_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">

<head dir="rtl">
    <meta charset="utf-8">
    <title>فروشگاه آنلاین زیبا مد</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css' %}"
          rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body dir="ltr">
<div>
</div>
<!-- Topbar Start -->
<div class="container-fluid">
    <div class="row bg-secondary py-1 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center h-100">
                <a class="text-body mr-3" href="">درباره ما</a>
                <a class="text-body mr-3" href="">ارتباط با ما</a>
                <a class="text-body mr-3" href="">کمک</a>
                <a class="text-body mr-3" href="">پرسش و پاسخ</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">صفحه من
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <button class="dropdown-item" type="button">ورود</button>
                        <button class="dropdown-item" type="button">ثبت نام</button>
                    </div>
                </div>
            </div>
            <div class="d-inline-flex align-items-center d-block d-lg-none">
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-heart text-dark"></i>
                    <span class="badge text-dark border border-dark rounded-circle"
                          style="padding-bottom: 2px;">0</span>
                </a>
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-shopping-cart text-dark"></i>
                    <span class="badge text-dark border border-dark rounded-circle"
                          style="padding-bottom: 2px;">0</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
        <div class="col-lg-4">
            <a href="" class="text-decoration-none">
                <span class="h1 text-uppercase text-primary bg-dark px-2">زیبا</span>
                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">مد</span>
            </a>
        </div>
        <div class="col-lg-4 col-6 text-left">
            <form action="{% url 'home_app:search' %}">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for products" name="search">
                    <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </span>
                    </div>
                </div>
            </form>
        </div>
        <div dir="rtl" class="col-lg-4 col-6 text-right">
            <p class="m-0">پل ارتباطی</p>
            <h5 dir="ltr" class="m-0">+989109278210</h5>
        </div>
    </div>
</div>
<!-- Topbar End -->


<!-- Navbar Start -->
<div dir="rtl" class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse"
               href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>دسته بندی</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light"
                 id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                <div class="navbar-nav w-100">
                    <div class="nav-item dropdown dropright">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">لباس<i
                                class="fa fa-angle-right float-right mt-1"></i></a>
                        <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                            <a href="" class="dropdown-item">لبایس مردانه</a>
                            <a href="" class="dropdown-item">لباس زنانه</a>
                            <a href="" class="dropdown-item">لباس بچه گانه</a>
                        </div>
                    </div>
                    <a href="" class="nav-item nav-link">پیراهن</a>
                    <a href="" class="nav-item nav-link">شلوار</a>
                    <a href="" class="nav-item nav-link">لباس زمستانه</a>
                    <a href="" class="nav-item nav-link">لباس خواب</a>
                    <a href="" class="nav-item nav-link">لباس ورزشی</a>
                    <a href="" class="nav-item nav-link">Jumpsuits</a>
                    <a href="" class="nav-item nav-link">Blazers</a>
                    <a href="" class="nav-item nav-link">ژاکت</a>
                    <a href="" class="nav-item nav-link">کفش</a>
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">زیبا</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">مد</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{% url 'home_app:home' %}" class="nav-item nav-link active">خانه</a>
                        <a href="{% url 'home_app:all_products' %}" class="nav-item nav-link">فروشگاه</a>
                        <a href="{% url 'home_app:sendmsg' %}" class="nav-item nav-link">ارتباط با ما</a>
                        <a href="{% url 'home_app:showcart' %}" class="nav-item nav-link">  سبد خرید</a>

                    </div>
                    <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                        <a href="" class="btn px-0">
                            <i class="fas fa-heart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle"
                                  style="padding-bottom: 2px;">0</span>
                        </a>
                        <a href="" class="btn px-0 ml-3">
                            <i class="fas fa-shopping-cart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle"
                                  style="padding-bottom: 2px;">0</span>
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- Navbar End -->
{% block content %}
{% endblock %}

<!-- Footer Start -->
<div class="container-fluid bg-dark text-secondary mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <h5 class="text-secondary text-uppercase mb-4">پل ارتباطی با ما</h5>
            <p class="mb-4">این فروشگاه با مجرب ترین افراد در نظر دارد بهترین خدمات را به شما ارائه دهد و شما را
                مطابق با سلیقه تان زیباتر کند.</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>شاهرود، میدان هفت تیر ،
                دانشگاه صنعتی شاهرود</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>ziba_mod@gmail.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+989109278210</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">خرید سریع</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>خانه</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>خرید
                            ما</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>حزئیات
                            خرید</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>سبد
                            خرید</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>صفحه شخصی</a>
                        <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>ارتباط با
                            ما</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">پروفایل من</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>خانه</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>خرید
                            ما</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>جزئیات
                            خرید</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>سبد
                            خرید</a>
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>صفحه شخصی</a>
                        <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>ارتباط با
                            ما</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">نظرات، پیششنهادات، انتقادات</h5>
                    <p>با ارسال ایمیل نظرات خود در بهبود کیفیت خدمات ما را یاری بفرمائید</p>

                    <h6 class="text-secondary text-uppercase mt-4 mb-3">ما را دنبال کنید</h6>
                    <div class="d-flex">
                        <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i
                                class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-primary btn-square mr-2" href="#"><i
                                class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-secondary">
                &copy; <a class="text-primary" href="#">zibamod</a>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="{% static 'img/payments.png' %}" alt="">
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


<!-- JavaScript Libraries -->
<script src="{% static 'https://code.jquery.com/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
<script src="{% static 'mail/contact.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>