home_app/urls.py
from django.urls import path
from . import views

app_name = 'home_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('detail<int:pk>', views.detail, name='detail'),
    path('addtocart<int:pk>', views.add_to_cart, name='addtocart'),
    path('deletefromcart<int:pk>', views.delete, name='deletefromcart'),
    path('womencategory', views.women_category, name='womencategory'),
    path('search', views.search, name='search'),
    path('sportcategory', views.sport_category, name='sportcategory'),
    path('sendmsg', views.send_msg, name='sendmsg'),
    path('showcart', views.show_cart,name='showcart'),
    path('showall', views.all_products,name='all_products')

]

modshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('', include('auth_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_app/models.py
from django.contrib.auth.models import User
from django.db import models



# Create your models here.
class Color(models.Model):
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.color


class Size(models.Model):
    size = models.CharField(max_length=20)

    def __str__(self):
        return self.size


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Product(models.Model):
    image = models.ImageField(upload_to='products')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    colors = models.ManyToManyField(Color)
    size = models.ManyToManyField(Size)

    def __str__(self):
        return self.name


class Order(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    size = models.CharField(max_length=10)
    color = models.CharField(max_length=10)
    total_price = models.IntegerField(default=0)
    price = models.IntegerField(null=True, blank=True)
    quantity = models.IntegerField(default=0)
    product_name = models.CharField(max_length=20)

    class Meta:
        unique_together = ('color', 'size', 'product_name', 'username')

    def __str__(self):
        return self.product_name


class Contact(models.Model):
    name = models.CharField(max_length=20)
    subj = models.CharField(max_length=30)
    msg = models.TextField()
    email = models.CharField(max_length=50)

    def __str__(self):
        return self.name

home_app/views.py
from django.contrib.auth import authenticate
from .models import Product, Order, Contact
from auth_app.models import ImageProcessing
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.core.paginator import Paginator

# Create your views here.

def home(request):
    products = Product.objects.all()
    order = Product.objects.raw('select * from modshopdb.home_app_product order by price DESC')
    return render(request, 'home_app/index.html', {'products': products, 'recent': order})


def detail(request, pk):
    instance = get_object_or_404(Product, id=pk)
    return render(request, 'home_app/detail.html', {'product': instance})


def add_to_cart(request, pk):
    if request.method == 'POST':
        product = Product.objects.get(id=pk)

        quantity, color, size = request.POST.get('quantity'), request.POST.get('color'), request.POST.get('size')
        product_exist = Order.objects.filter(username=request.user, color=color, size=size,
                                             product_name=product.name).exists()
        instance = Order.objects.filter(username=request.user, color=color, size=size,
                                        product_name=product.name)
        print(request.user)

        if product_exist:
            print('ok')
            for order in instance:
                order.quantity += int(quantity)
                print('test2')
                order.total_price += int(quantity) * int(product.price)
                order.save()

        else:
            print('no')

            new_instance = Order.objects.create(username=request.user, color=color, size=size,
                                                product_name=product.name,
                                                quantity=int(quantity), price=int(product.price))
            print('test')
            new_instance.total_price += (int(quantity) * int(new_instance.price))
            new_instance.save()

        products = Order.objects.filter(username=request.user)
        total_prices = 0
        for order in products:
            total_prices += order.total_price

        return render(request, 'home_app/cart.html', {'products': products, 'total': total_prices})
    products = Order.objects.filter(username=request.user)
    total_prices = 0
    for order in products:
        total_prices += order.total_price

    return render(request, 'home_app/cart.html', {'products': products, 'total': total_prices})


def delete(request, pk):
    Order.objects.get(id=pk).delete()
    products = Order.objects.filter(username=request.user)
    total_prices = 0
    for order in products:
        total_prices += order.total_price
    return render(request, 'home_app/cart.html', {'products': products, 'total': total_prices})


def women_category(request):
    search_products = Product.objects.filter(category__name='women')
    products = Product.objects.all()
    order = Product.objects.raw('select * from modshopdb.home_app_product order by price DESC')
    return render(request, 'home_app/index.html', {'products': products, 'recent': order, 'search': search_products})


def sport_category(request):
    search_products = Product.objects.filter(category__name='sport')
    products = Product.objects.all()
    order = Product.objects.raw('select * from modshopdb.home_app_product order by price DESC')
    return render(request, 'home_app/index.html', {'products': products, 'recent': order, 'search': search_products})


def search(request):
    name = request.GET.get('search')
    print(name)
    search_products = Product.objects.raw('select * from modshopdb.home_app_product where name LIKE %s', [f'%{name}%'])
    products = Product.objects.all()
    order = Product.objects.raw('select * from modshopdb.home_app_product order by price DESC')
    return render(request, 'home_app/index.html', {'products': products, 'recent': order, 'search': search_products})


def send_msg(request):
    if request.method == 'POST':
        name, subj, msg, email = request.POST.get('name'), request.POST.get('subj'), request.POST.get(
            'msg'), request.POST.get('email')
        Contact.objects.create(name=name, subj=subj, msg=msg, email=email)
        return render(request, 'home_app/contact.html')

    return render(request, 'home_app/contact.html')


def show_cart(request):
    products = Order.objects.filter(username=request.user)
    total_prices = 0
    for order in products:
        total_prices += order.total_price
    return render(request, 'home_app/cart.html', {'products': products, 'total': total_prices})


def all_products(request):
    colors, sizes, min_price, max_price = request.GET.getlist('color'), request.GET.getlist('size'), request.GET.get(
        'min'), request.GET.get('max')

    products = Product.objects.all()
    if colors:
        products = products.filter(colors__color__in=colors).distinct()
    if sizes:
        products = products.filter(size__size__in=sizes).distinct()
    if max_price and min_price:
        max = int(max_price)
        min = int(min_price)
        products = products.raw('select * from modshopdb.home_app_product where price > %s and price < %s',
                                [min, max])
    paginator = Paginator(products, 1)
    page = request.GET.get('page')
    obj = paginator.get_page(page)

    return render(request, 'home_app/shop.html', {'products': obj})

home_app/templates/home_app/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shopping Cart</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Cart Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                <tr>
                    <th>Products</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Remove</th>
                </tr>
                </thead>
                <tbody class="align-middle">
                {% for item in products %}

                    <tr>
                        <td class="align-middle"><img src="" alt=""
                                                      style="width: 50px;">{{ item.product_name }}</td>
                        <td class="align-middle">{{ item.price }} $</td>


                        <td class="align-middle">{{ item.quantity }}</td>

                        <td class="align-middle">{{ item.total_price }} $</td>
                        <td class="align-middle"><a href="{% url 'home_app:deletefromcart' item.id %}" class="alert-danger">remove</a></td>


                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-30" action="">
                <div class="input-group">
                    <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <h5 class="section-title position-relative text-uppercase mb-3"><span
                    class="bg-secondary pr-3">Cart Summary</span></h5>
            <div class="bg-light p-30 mb-5">
                <div class="border-bottom pb-2">
                    <div class="d-flex justify-content-between mb-3">
                        <h6>Subtotal</h6>
                        <h6></h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">$10</h6>
                    </div>
                </div>
                <div class="pt-2">
                    <div class="d-flex justify-content-between mt-2">
                        <h5>Total</h5>
                        <h5>{{ total }} $</h5>
                    </div>
                    <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->
{% endblock %}

home_app/templates/home_app/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">Home</a>
                    <span class="breadcrumb-item active">Contact</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Contact Start -->
    <div class="container-fluid">
        <h2 class="section-title position-relative text-uppercase text-center mx-xl-5 mb-4"><span class="bg-secondary pr-3">Contact Us</span></h2>
        <div class=" px-xl-5">
            <div class=" mb-5 contact-us" style="">
                <div class="contact-form bg-light p-30">
                    <div id="success"></div>
                    <form name="sentMessage" id="contactForm" novalidate="novalidate" action="{% url 'home_app:sendmsg' %} " method="post">
                        {% csrf_token %}
                        <div class="control-group">
                            <input name="name" type="text" class="form-control" id="name" placeholder="Your Name"
                                required="required" data-validation-required-message="Please enter your name" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input  name="email" type="email" class="form-control" id="email" placeholder="Your Email"
                                required="required" data-validation-required-message="Please enter your email" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input name="subj" type="text" class="form-control" id="subject" placeholder="Subject"
                                required="required" data-validation-required-message="Please enter a subject" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <textarea name="msg" class="form-control" rows="8" id="message" placeholder="Message"
                                required="required"
                                data-validation-required-message="Please enter your message"></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">Send
                                Message</button>
                        </div>
                    </form>
                </div>
            </div>
           
        </div>
    </div>
    <!-- Contact End -->
{% endblock %}

home_app/templates/home_app/shop.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">Home</a>
                    <a class="breadcrumb-item text-dark" href="#">Shop</a>
                    <span class="breadcrumb-item active">Shop List</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <!-- Shop Sidebar Start -->
            <div class="col-lg-3 col-md-4">
                <!-- Price Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by price</span>
                </h5>
                <div class="bg-light p-4 mb-30">
                    <form action="{% url 'home_app:all_products' %}">
                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <label for="price-all">min</label>
                            <input name="min" type="number" checked id="price-all">
                        </div>

                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                            <label for="price-all">max</label>
                            <input type="number" name="max" checked id="price-all">
                        </div>

                </div>
                <!-- Price End -->

                <!-- Color Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by color</span>
                </h5>
                <div class="bg-light p-4 mb-30">

                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input name="color" value="black" type="checkbox" class="custom-control-input" id="color-1">
                        <label class="custom-control-label" for="color-1">Black</label>
                        <span class="badge border font-weight-normal">150</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input name="color" value="white" type="checkbox" class="custom-control-input" id="color-2">
                        <label class="custom-control-label" for="color-2">White</label>
                        <span class="badge border font-weight-normal">295</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input name="color" value="red" type="checkbox" class="custom-control-input" id="color-3">
                        <label class="custom-control-label" for="color-3">Red</label>
                        <span class="badge border font-weight-normal">246</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input name="color" value="blue" type="checkbox" class="custom-control-input" id="color-4">
                        <label class="custom-control-label" for="color-4">Blue</label>
                        <span class="badge border font-weight-normal">145</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                        <input name="color" value="green" type="checkbox" class="custom-control-input" id="color-5">
                        <label class="custom-control-label" for="color-5">Green</label>
                        <span class="badge border font-weight-normal">168</span>
                    </div>

                </div>
                <!-- Color End -->

                <!-- Size Start -->
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by size</span>
                </h5>
                <div class="bg-light p-4 mb-30">
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input name="size" value="XS" type="checkbox" class="custom-control-input" id="size-1">
                        <label class="custom-control-label" for="size-1">XS</label>
                        <span class="badge border font-weight-normal">150</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input name="size" value="S" type="checkbox" class="custom-control-input" id="size-2">
                        <label class="custom-control-label" for="size-2">S</label>
                        <span class="badge border font-weight-normal">295</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input name="size" value="M" type="checkbox" class="custom-control-input" id="size-3">
                        <label class="custom-control-label" for="size-3">M</label>
                        <span class="badge border font-weight-normal">246</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input name="size" value="L" type="checkbox" class="custom-control-input" id="size-4">
                        <label class="custom-control-label" for="size-4">L</label>
                        <span class="badge border font-weight-normal">145</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                        <input name="size" value="XL" type="checkbox" class="custom-control-input" id="size-5">
                        <label class="custom-control-label" for="size-5">XL</label>
                        <span class="badge border font-weight-normal">168</span>
                    </div>
                    <input type="submit" value="send">
                    </form>
                </div>
                <!-- Size End -->
            </div>
            <!-- Shop Sidebar End -->


            <!-- Shop Product Start -->
            <div class="col-lg-9 col-md-8">
                <div class="row pb-3">
                    <div class="col-12 pb-1">
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <div>
                                <button class="btn btn-sm btn-light"><i class="fa fa-th-large"></i></button>
                                <button class="btn btn-sm btn-light ml-2"><i class="fa fa-bars"></i></button>
                            </div>
                            <div class="ml-2">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                            data-toggle="dropdown">Sorting
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="#">Latest</a>
                                        <a class="dropdown-item" href="#">Popularity</a>
                                        <a class="dropdown-item" href="#">Best Rating</a>
                                    </div>
                                </div>
                                <div class="btn-group ml-2">
                                    <button type="button" class="btn btn-sm btn-light dropdown-toggle"
                                            data-toggle="dropdown">Showing
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right">
                                        <a class="dropdown-item" href="#">10</a>
                                        <a class="dropdown-item" href="#">20</a>
                                        <a class="dropdown-item" href="#">30</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% for item in products %}
                        <div class="col-lg-4 col-md-6 col-sm-6 pb-1">
                            <div class="product-item bg-light mb-4">
                                <div class="product-img position-relative overflow-hidden">
                                    <img class="img-fluid w-100" src="{{ item.image.url }}" alt="">
                                    <div class="product-action">
                                        <a class="btn btn-outline-dark btn-square" href=""><i
                                                class="fa fa-shopping-cart"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i
                                                class="fa fa-sync-alt"></i></a>
                                        <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
                                    </div>
                                </div>
                                <div class="text-center py-4">
                                    <a class="h6 text-decoration-none text-truncate"
                                       href="{% url 'home_app:detail' item.id %}">{{ item.name }}</a>
                                    <div class="d-flex align-items-center justify-content-center mt-2">
                                        <h5>{{ item.price }} $</h5>
                                        <h6 class="text-muted ml-2">
                                            <del></del>
                                        </h6>
                                    </div>

                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    <div class="col-12">
                        {% if products.has_other_pages %}
                            <nav>
                                <ul class="pagination justify-content-center">
                                    {% if products.has_previous %}
                                         <li class="page-item"><a class="page-link"
                                                                 href="?page={{ products.previous_page_number }}">Previous</a>
                                        </li>
                                    {% endif %}
                                    {% for i in products.paginator.page_range %}
                                        {% if products.number == i %}
                                            <li class="page-item active"><a class="page-link"
                                                                            href="?page={{ i }}">{{ i }}</a></li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                            </li>
                                        {% endif %}

                                    {% endfor %}
                                    {% if products.has_next %}
                                        <li class="page-item"><a class="page-link"
                                                                 href="?page={{ products.next_page_number }}">Next</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        {% endif %}
                    </div>
                </div>
            </div>
            <!-- Shop Product End -->
        </div>
    </div>
    <!-- Shop End -->
{% endblock %}