auth_app/urls.py
from django.urls import path
from . import views

app_name = 'auth_app'
urlpatterns = [
    path('login', views.image_processing, name='image_processing'),
    path('logout', views.log_out, name='logout'),
    path('register', views.Register, name='register'),
]

modshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('', include('auth_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth_app/models.py
from django.db import models


# Create your models here.

class ImageProcessing(models.Model):
    unique_code = models.CharField(max_length=20, unique=True)
    image = models.ImageField()

auth_app/forms.py
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20,widget=forms.TextInput(attrs={'class': 'input100'}))
    image = forms.ImageField()

auth_app/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
import cv2
from .forms import RegisterForm

# Create your views here.
from .models import ImageProcessing
from deepface import DeepFace


def compare_faces(user, database_image_path):
    result = DeepFace.verify(user, database_image_path)
    return result["verified"]


def image_processing(request):
    if request.method == 'POST':
        pk = request.POST.get('pk')
        print(pk)

        cap = cv2.VideoCapture(0)

        if not cap.isOpened():
            print("unable to access the camera")
            exit()

        ret, frame = cap.read()

        if ret:

            instance = ImageProcessing.objects.get(unique_code=pk)
            location = f'.{instance.image.url}'

            image_path = "user_image.jpg"
            cv2.imwrite(image_path, frame)
            if compare_faces(image_path, location) == True:
                return redirect('/')
            else:
                return HttpResponse("access denied")

        cap.release()
        cv2.destroyAllWindows()
    else:
        return render(request, 'auth_app/index.html')


def Register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            ImageProcessing.objects.create(unique_code=data['username'], image=data['image'])

        return render(request, 'home_app/index.html')


    else:
        return render(request, 'auth_app/register.html', {'form': form})


def log_out(request):
    logout(request)
    return render(request, 'auth_app/index.html')

auth_app/templates/auth_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V3</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'assets/images/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'assets/fonts/iconic/css/material-design-iconic-font.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/animsition/css/animsition.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/daterangepicker/daterangepicker.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
    <!--===============================================================================================-->
</head>
<body>

<div class="limiter">
    <div class="container-login100" style="background-image: url('{% static 'assets/images/bg-01.jpg' %}');">
        <div class="wrap-login100">
            <form class="login100-form validate-form" action="{% url 'auth_app:image_processing' %}" method="post">
                {% csrf_token %}
                <span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

                <span class="login100-form-title p-b-34 p-t-27">
						Log in
					</span>

                <div class="wrap-input100 validate-input" data-validate="Enter username">
                    <input class="input100" type="text" name="pk" placeholder="Username">
                    <span class="focus-input100" data-placeholder="&#xf207;"></span>
                </div>


                <div class="contact100-form-checkbox">
                    <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                    <label class="label-checkbox100" for="ckb1">
                        Remember me
                    </label>
                </div>

                <div class="container-login100-form-btn">
                    <button class="login100-form-btn">
                        Login
                    </button>
                </div>

                <div class="text-center p-t-90">
                    <a class="txt1" href="#">
                        Forgot Password?
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
<script src="{% static 'assets/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'assets/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'assets/vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'assets/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'assets/vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'assets/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'assets/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

auth_app/templates/auth_app/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V3</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'assets/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static 'assets/images/bg-01.jpg' %}');">
			<div class="wrap-login100">
				<form class="login100-form validate-form" action="{% url 'auth_app:register' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						Register
					</span>

				{{ form.as_p }}

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Register
						</button>
					</div>


				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'assets/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'assets/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'assets/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'assets/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'assets/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'assets/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'assets/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>